### ISSUE TITLE
Questions regarding images.

### ISSUE THREAD

**Issue by tschettervictor** [DtxdF/AppJail#19] opened 2024-11-30 04:46 UTC
Greetings,

What all is included in .image files?
Why is it necessary to download the image files?
Is that the only option?
Can one specify to install from scratch without the image?
Do makejails support reinstalling overtop of already existing data contained in mount points?

If you could point me to a detailed description of what happens when doing a makejail install, that would be great.

Sorry if these are silly questions, but I like to know all the ins and out of software I’m using.

Thanks again for your time.

**Comment by DtxdF** [comment] 2024-11-30 19:25
> What all is included in .image files?

```console
# mkdir /tmp/k
# archivemount -o ro /usr/local/appjail/cache/images/uptime_kuma/14.1-amd64-image.appjail /tmp/k
# tree -L 1 /tmp/k
/tmp/k
├── conf
├── init
└── jail

3 directories, 1 file
# tree /tmp/k/conf
/tmp/k/conf
├── config.conf
└── volumes
    ├── uptimekuma-data
    │   ├── gid
    │   ├── mountpoint
    │   ├── type
    │   └── uid
    ├── uptimekuma-db
    │   ├── gid
    │   ├── mountpoint
    │   ├── type
    │   └── uid
    └── uptimekuma-server
        ├── gid
        ├── mountpoint
        ├── type
        └── uid

5 directories, 13 files
# wc -l /tmp/k/init
      13 /tmp/k/init
```

The **InitScript**, the `config.conf` file, `volumes` and the jail directory.

> Why is it necessary to download the image files?
> Is that the only option?
> Can one specify to install from scratch without the image?

The image is only needed if a Makejail contains the `FROM` instruction. Makejails like [redis](https://github.com/AppJail-makejails/redis/blob/main/Makejail) do not contain such an instruction, but Makejails like [darkhttpd](https://github.com/AppJail-makejails/darkhttpd/blob/main/Makejail#L5) (or most of them) do.

Why do I prefer images to no images? Images have more advantages than disadvantages.

* If you download an image, it works as a big cache for all the packages and files of the service you want to deploy, since you don't need to make any request using `pkg(8)`, `pip`, `npm` or something similar depending on the application inside the jail.
* Images are not re-downloaded unless the AJSPEC file indicates otherwise, and is a process automatically performed by `appjail-image(1)`.
* “Build Once, Deploy Everytime” is the motto. I take care of building the images from time to time and this has the advantage that you, the user, do not need to build the image. This is not just exporting files inside the jail, I also need to compile files if I need to compile, install packages, configure some things, etc., etc. This is, of course, automating.
* Images improve the performance, at least, at creation time.
* This is very, very necessary if the user follows the [Ephemeral Concept](https://man.freebsd.org/cgi/man.cgi?query=appjail-ephemeral&apropos=0&sektion=0&manpath=FreeBSD+13.4-RELEASE+and+Ports&arch=default&format=html).

On the contrary, if the images do not exist, the user needs to compile programs or obtain `pkg(8)` packages, pip dependencies, compose dependencies, npm dependencies, etc., depending on the application inside the jail. This is unacceptable. And somewhat necessary for tools like [Director](https://github.com/DtxdF/Director).

> Do makejails support reinstalling overtop of already existing data contained in mount points?

Yeah, using the PseusoFS filesystem:

* https://appjail.readthedocs.io/en/latest/fs-mgmt/#pseudofs

PseudoFS is not a file system (that's why its name contains the word *pseudo*), but it was implemented because `unionfs(5)` is not yet production ready as far as I understand, but I consider `unionfs(5)` to be the most appropriate file system for these things. But if the improvements to `unionfs(5)` make it production ready, you can use it without any problem like any other file system in AppJail.

> If you could point me to a detailed description of what happens when doing a makejail install, that would be great.

I will explain this at a high level because the documentation and man pages explain this with more details.

1. It creates `build.makejail` which contains the instructions that customizes the image. It compile the software, install dependencies with any package manager or dependencies needed by the application, etc.
2. The image is created using the jail created by the `build.makejail`.
3. I send the image to the mirrors.
4. The AJSPEC file generated when creating the image is placed in the repository containing the Makejails, files, etc.
5. `Makejail` is created containing the `FROM` instruction to download and import the image from the mirror. It will validate that the image is not corrupted using the checksum specified by the AJSPEC. This Makejail automates the configuration of the service and starts it normally.
6. You have a jail with your service configured and started.

Currently I do not build images manually, this is unfeasible. I have created [Reproduce](https://github.com/DtxdF/reproduce) to build images and [multi-reproduce](https://github.com/DtxdF/multi-reproduce) to build images in bulk, which includes updating the AJSPEC file and so on.

**Comment by tschettervictor** [comment] 2024-11-30 21:01
That does make sense.

What about things like Nextcloud where you need a database, etc…

I imagine the image has the database program (MariaDB/PostgreSQL) already installed. And all that’s left is for the database to be created.

**Comment by DtxdF** [comment] 2024-11-30 21:32
A different jail is deployed with the database supported by the application. See the [Nextcloud](https://github.com/AppJail-makejails/nextcloud) Makejail README for an example.

**Comment by DtxdF** [comment] 2024-11-30 23:44
Can this issue be marked as fixed?

**Closed** 2024-11-30 23:45 UTC

**Comment by tschettervictor** [comment] 2024-11-30 23:47
I’ll close this, but still having issues getting to to run even with Apache. Will update on the Nextcloud Appjail page.

**Comment by DtxdF** [comment] 2024-12-01 00:01
If you are willing to experiment deploying Nextcloud, no problem, but you should be aware that Nextcloud is very, very complex even with tools like Docker or AppJail, so I recommend that you familiarize yourself with AppJail and FreeBSD before proceeding with the Nextcloud monster.

**Comment by tschettervictor** [comment] 2024-12-01 00:08
I’m fairly familiar with it. Im fairly well acquainted with the things that need to be in place. See the script in the “bsd-apps” repo.

I’m running multiple instances managing over a million files for people. Moving to Appjail (if I so choose) will be the fun part.

**Comment by DtxdF** [comment] 2024-12-01 00:18
Great!
